apiVersion: v1
kind: Service
metadata:
  name: k8s-bg
  labels:
    name: k8s-bg
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8050
  selector:
    name: k8s-bg
    version: v2
