---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bg
  labels:
    name: k8s-bg
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bg
      labels:
        name: k8s-bg
        version: gunns
    spec:
      containers:
      - image: dockergunn/bg:v2.2
        name: k8s-bg
        ports:
        - name: k8s-bg
          containerPort: 80    
