apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bg
  labels:
    name: k8s-bg
spec:
  replicas: 3
  selector:
    matchLabels:
      name: k8s-bg
      version: blue
  template:
    metadata:
      name: k8s-bg
      labels:
        name: k8s-bg
        version: blue
    spec:
      containers:
      - image: dockergunn/bg:v1.2
        name: k8s-bg
        ports:
        - name: k8s-bg
          containerPort: 80    
